import Head from "next/head"

import Avatar from "../components/Avatar"

import { ViewGridIcon, MicrophoneIcon } from "@heroicons/react/solid"
import { SearchIcon } from "@heroicons/react/outline"
import Image from "next/image"
import Footer from "../components/Footer"
import { useRef } from "react"
import { useRouter } from "next/router"

export default function Home() {
  const router = useRouter()
  const searchInputRef = useRef(null)

  const search = (e) => {
    e.preventDefault()

    const term = searchInputRef.current.value

    if (!term) return

    router.push(`/search?term=${term}`)
  }

  return (
    <div className="flex flex-col h-screen justify-center items-center">
      <Head>
        <title>Google-2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex justify-between w-full p-5 text-sm text-gray-700 ">
        {/* left div */}
        <div className="flex items-center space-x-4">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* right div */}

        <div className="flex space-x-4 items-center ">
          <p className="link">Gmail</p>
          <p className="link"> Images</p>

          {/* Icons */}
          <ViewGridIcon className="w-10 h-10 p-2  rounded-full hover:bg-gray-200 cursor-pointer" />

          {/* Avatar */}
          <Avatar url="https://images.unsplash.com/photo-1560343776-97e7d202ff0e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YXZlbmdlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60" />
        </div>
      </header>

      {/* Body */}

      <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
        <Image
          src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          width={300}
          height={100}
          alt="image"
        />

        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border  border-gray-200 px-5 py-3  items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className=" focus:outline-none flex-grow"
          />
          <MicrophoneIcon className="h-5 text-gray-500" />
        </div>
        <div className="flex flex-col space-y-2 w-1/2 justify-center mt-8 sm:flex-row sm:space-x-4 ">
          <button className="btn" onClick={search}>
            Google Search
          </button>
          <button className="btn" onClick={search}>
            I&apos;m Feeling Lucky
          </button>
        </div>
      </form>

      {/* Footer */}
      <Footer />
    </div>
  )
}
